# Generated by Django 4.2.3 on 2023-09-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
    ]
